name = "krl-kr-email"
main = "worker.js"
compatibility_date = "2024-01-01"

# Deployed at: krl-kr-email.rukkit.workers.dev
# Email routing trigger — catches all *@krl.kr emails
[[email]]
routing_to = "worker"
